version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: payment_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payment_manager
      MYSQL_USER: adonis
      MYSQL_PASSWORD: adonis
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
